hunter_config(ZLIB VERSION 1.2.8-p3
              CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=TRUE)
hunter_config(Protobuf VERSION 3.12.3-li0)
hunter_config(absl VERSION 20200225.2 CMAKE_ARGS
  CMAKE_POSITION_INDEPENDENT_CODE=TRUE
  )
hunter_config(OpenSSL VERSION 1.1.1c CMAKE_ARGS
  CMAKE_POSITION_INDEPENDENT_CODE=TRUE
  )
hunter_config(c-ares VERSION 1.14.0-p0 CMAKE_ARGS
  CARES_STATIC=TRUE
  CARES_SHARED=FALSE
  CARES_STATIC_PIC=TRUE
  )
hunter_config(gRPC VERSION 1.30.0-li0 CMAKE_ARGS
  gRPC_BUILD_GRPC_PYTHON_PLUGIN=OFF
  gRPC_BUILD_GRPC_RUBY_PLUGIN=OFF
  gRPC_BUILD_GRPC_PHP_PLUGIN=OFF
  gRPC_BUILD_GRPC_OBJECTIVE_C_PLUGIN=OFF
  gRPC_BUILD_GRPC_NODE_PLUGIN=OFF
  gRPC_BUILD_GRPC_CSHARP_PLUGIN=OFF
  )
